name: Build and Deploy to Sandbox Environment on CloudHub
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(echo $artifactName1 | sed "s/.jar/-$commitHash.jar/")
          mv $artifactName1 $artifactName2
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Configure Anypoint Platform Credentials
        run: |
            mkdir -p ~/.m2
            echo "<settings>
                  <servers>
                    <server>
                      <id>anypoint-exchange</id>
                      <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                      <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
      - name: Deploy to CloudHub 2.0
        env:
          ANYPOINT_USERNAME: '${{ secrets.ANYPOINT_USERNAME }}'
          ANYPOINT_PASSWORD: '${{ secrets.ANYPOINT_PASSWORD }}'
          ANYPOINT_ENV_ID: '${{ secrets.ANYPOINT_ENV_ID }}'
          ANYPOINT_ORG_ID: '${{ secrets.ANYPOINT_ORG_ID }}'
        run: |
          mvn clean deploy \
          -DmuleDeploy \
          -Danypoint.username=$ANYPOINT_USERNAME \
          -Danypoint.password=$ANYPOINT_PASSWORD \
          -Danypoint.envId=$ANYPOINT_ENV_ID \
          -Danypoint.orgId=$ANYPOINT_ORG_ID
