name: Deploy Mule App to CloudHub 2.0

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.4.1
        with:
          maven-version: '3.9.6'

      - name: Configure Anypoint Platform Credentials
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>anypoint-exchange</id>
                      <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                      <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Deploy to CloudHub 2.0
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ENV_ID: ${{ secrets.ANYPOINT_ENV_ID }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
        run: |
          mvn clean deploy \
            -DmuleDeploy \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.envId=$ANYPOINT_ENV_ID \
            -Danypoint.orgId=$ANYPOINT_ORG_ID
